BaseURL = 'https://www.alexstrong.design/'
languageCode = 'en-us'
title = 'The Big Walkabout'
theme = 'PaperMod'
canonifyURLs = true
relativeURLs = true

# SEO for web crawling
[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
    # Simple values first
    title = "The Big Walkabout | Alex Strong"
    description = "Documenting a bikepacking journey through the landscapes of New Zealand."
    keywords = ["New Zealand", "Bikepacking", "Photography", "Te Araroa", "Alex Strong", "Travel Blog", "Alex Strong Design"]
    author = "Alex Strong"
    defaultTheme = "auto"
    showCodeCopyButtons = true
    socialInHeader = true
    # This replaces the broken [params.images] section
    images = ["profile.jpg"]

    # FAVICONS (A sub-table)
    [params.assets]
      favicon = "favicon.ico"
      favicon16x16 = "favicon-16x16.png"
      favicon32x32 = "favicon-32x32.png"
      apple_touch_icon = "apple-touch-icon.png"
      safari_pinned_tab = "safari-pinned-tab.svg"
      android_chrome_192 = "android-chrome-192x192.png"
      android_chrome_512 = "android-chrome-512x512.png"

    # HOME INFO SECTION (A sub-table)
    [params.homeInfoParams]
        Title = "Welcome to The Big Walkabout"
        Content = "I'm bikepacking New Zealand.\n\nCheck out my [latest posts](/posts) or [subscribe](/subscribe) to get updates in your inbox.\n\nYou can track my progress on [Strava](https://www.strava.com/athletes/25085850) as well."

# SOCIAL ICONS (Global table)
[[params.socialIcons]]
    name = "rss"
    url = "/index.xml"

[[params.socialIcons]]
    name = "email"
    url = "https://buttondown.email/AlexStrong"

[[params.socialIcons]]
    name = "strava"
    url = "https://www.strava.com/athletes/YOUR_ID"

# NAVIGATION MENU
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 5

[[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    weight = 10

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 15

[[menu.main]]
    identifier = "subscribe"
    name = "Newsletter"
    url = "/subscribe/"
    weight = 20

# IMAGE PROCESSING
[imaging]
    quality = 75
    resampleFilter = "CatmullRom"

# RSS SETTINGS
[rss]
    fullContent = true

# FOR FIXING AN IMAGE BUG
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

